// <auto-generated />
using Axerrio.DDD.Menu.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Axerrio.DDD.Menu.Migrations
{
    [DbContext(typeof(MenuContext))]
    [Migration("20171206152551_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("Relational:Sequence:dbo.MenuId", "'MenuId', 'dbo', '1', '5', '', '', 'Int32', 'False'")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Axerrio.DDD.Menu.Domain.AggregatesModel.MenuAggregate.Menu", b =>
                {
                    b.Property<int>("Identity")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("MenuId")
                        .HasAnnotation("SqlServer:HiLoSequenceName", "MenuId")
                        .HasAnnotation("SqlServer:HiLoSequenceSchema", "dbo")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.SequenceHiLo);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<int>("Id");

                    b.Property<int>("MenuStatusId");

                    b.HasKey("Identity");

                    b.HasIndex("Id");

                    b.ToTable("Menus","dbo");
                });

            modelBuilder.Entity("Axerrio.DDD.Menu.Domain.AggregatesModel.MenuAggregate.MenuStatus", b =>
                {
                    b.Property<int>("Id");

                    b.Property<int?>("MenuStatusId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.HasKey("Id");

                    b.HasIndex("MenuStatusId");

                    b.ToTable("MenuStatus","dbo");
                });

            modelBuilder.Entity("Axerrio.DDD.Menu.Domain.AggregatesModel.MenuAggregate.Menu", b =>
                {
                    b.HasOne("Axerrio.DDD.Menu.Domain.AggregatesModel.MenuAggregate.MenuStatus", "MenuStatus")
                        .WithMany()
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Axerrio.DDD.Menu.Domain.AggregatesModel.MenuAggregate.MenuStatus", b =>
                {
                    b.HasOne("Axerrio.DDD.Menu.Domain.AggregatesModel.MenuAggregate.MenuStatus")
                        .WithMany("Items")
                        .HasForeignKey("MenuStatusId");
                });
#pragma warning restore 612, 618
        }
    }
}
