// <auto-generated />
using Axerrio.DDD.Menu.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Axerrio.DDD.Menu.Migrations
{
    [DbContext(typeof(MenuContext))]
    partial class MenuContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Axerrio.DDD.Menu.Domain.AggregatesModel.MenuAggregate.Menu", b =>
                {
                    b.Property<int>("Identity")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("MenuId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<int>("MenuStatusId");

                    b.HasKey("Identity");

                    b.HasIndex("MenuStatusId");

                    b.ToTable("Menus","dbo");
                });

            modelBuilder.Entity("Axerrio.DDD.Menu.Domain.AggregatesModel.MenuAggregate.MenuStatus", b =>
                {
                    b.Property<int>("Id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.HasKey("Id");

                    b.ToTable("MenuStatus","dbo");
                });

            modelBuilder.Entity("Axerrio.DDD.Menu.Domain.AggregatesModel.MenuAggregate.Menu", b =>
                {
                    b.HasOne("Axerrio.DDD.Menu.Domain.AggregatesModel.MenuAggregate.MenuStatus", "MenuStatus")
                        .WithMany()
                        .HasForeignKey("MenuStatusId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
