version: '3'

services:
  sts:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  id-sts:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
